<a href="https://colab.research.google.com/github/omgchan/ML-Journey/blob/main/Numpy_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [114]:
#importing numpy
import numpy as np

###Creating Arrays

In [115]:
x = [1, 2, 3] #is a list

In [116]:
y = np.array(x)  #converting a python list into a numpy array
y

array([1, 2, 3])

In [117]:
np.arange(1, 11) #just like a range function in python, arange creates an array with the given range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [118]:
np.arange(2, 10).reshape((4,2)) # reshape function takes a tuple as a parameter to create a matrix of the certain size

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [119]:
np.arange(1,10,2)  #like range(inital, final, gaps)

array([1, 3, 5, 7, 9])

In [120]:
np.ones((2,2)) #intializes each element to one

array([[1., 1.],
       [1., 1.]])

In [121]:
np.zeros((4,2)) #intializes each element to zero

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [122]:
np.random.random((3,2)) #creates an random for each element in the given size of matrix

array([[0.82507316, 0.41397148],
       [0.24330851, 0.41233924],
       [0.21846834, 0.0820631 ]])

In [123]:
np.linspace(-1,1,8) #linespace(intial, final, each gaps)

array([-1.        , -0.71428571, -0.42857143, -0.14285714,  0.14285714,
        0.42857143,  0.71428571,  1.        ])

In [124]:
np.identity(4) #creates an identity matrix is x squared size

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

###Arrays Attributes

In [125]:
a1 = np.arange(10, dtype=np.int32)
a2 = np.arange(10, dtype=float).reshape((5,2))
a3 = np.arange(8).reshape((2,2,2))  # first 2 = 2 2d arrays of 2*2

In [126]:
# ndim gives the dimension of an array
print(a1.ndim)  #1D array
print(a2.ndim) #2D array
a3.ndim #3D array

1
2


3

In [127]:
#shape
a2.shape

(5, 2)

In [128]:
#size

a2.size  #total number of items

10

In [129]:
a2.itemsize  #how much memory does each element use

8

In [130]:
#dtype

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


###Changing Datatypes

#

In [131]:
#astype

a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

###Array operations


In [132]:
x1 = np.arange(12).reshape((3,4))
x2 = np.arange(12,24).reshape((3,4))
x1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [133]:
#scalar operation
x1 + 2 #addition
x1 * 2  #scalar multiplication
2 * x1
x1 / 2
x1 ** 2





array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [134]:
#vector operations

x1 + x2
x1 * x2


array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

###Array Function


In [135]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[85., 79., 36.],
       [66., 35., 15.],
       [37., 69., 38.]])

In [136]:
#min, max, sum, prod

a1.min() #or np.min(a1)
a1.max()
np.sum(a1)
np.prod(a1)

np.min(a1, axis=0) #column wise min; axis = 0 mean col
np.min(a1, axis=1) #row wise min; axis = 1 mean row

array([36., 15., 37.])

In [137]:
np.mean(a1)
a1.std()


np.float64(22.683544914244408)

In [138]:
s2 = np.arange(12).reshape((3,4))
s3 = np.arange(16).reshape((4,4))


In [139]:
np.dot(s2, s3) #dot product

array([[ 56,  62,  68,  74],
       [152, 174, 196, 218],
       [248, 286, 324, 362]])

In [140]:
#round/floor/ceil

np.round(np.random.random((2,3))*100)


array([[18., 99., 90.],
       [ 2., 87., 61.]])

In [141]:
np.ceil(np.random.random((2,3))*100).astype(np.int32) #ceiling

array([[37, 95, 50],
       [80, 76, 20]], dtype=int32)

In [142]:
np.floor(np.random.random((2,3))*100).astype(np.int32)

array([[51, 43, 10],
       [92, 54, 84]], dtype=int32)

###INDEXING AND SLICING

In [143]:
a1= np.arange(10)
a2 = np.arange(12).reshape((3,4))
a3 = np.arange(8).reshape((2,2,2))

In [147]:
print(a1, "\n")
print(a2, "\n")
print(a3, "\n")



[0 1 2 3 4 5 6 7 8 9] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 



In [151]:
#indexing: indexing in 1D array is same as indexing in python
print (a1[1])
print (a1[-1])



1
9


In [154]:
#For 2D array, we use the index of element by their rows and columns (aij)
a2[1,2] #accssing 6 which is in the 2nd row(index 1) and 3rd col(index 2)

np.int64(6)

In [157]:
#For 3D arrays, first we identify which matrix has the element and use the same concept used in 2D array(matrix)
a3[1,1,0] #accessing 6

np.int64(6)

In [158]:
#slicing
#For 1D array, the concept of slicing is same as python
a1[1:4]

array([1, 2, 3])

In [159]:
a1[1:4:2]

array([1, 3])

In [160]:
a1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [161]:
#For 2D array, the concept is same but have to use in terms of rows and columns
a2[0, :]  #accesing all the elements of the first row



array([0, 1, 2, 3])

In [162]:
a2[:, 2] #accessing all the elements of the 3 column

array([ 2,  6, 10])

In [163]:
#using silicing you can get multiple datas
a2[:, 1: ]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [166]:
a2[::2, :3:2]

array([[ 0,  2],
       [ 8, 10]])

In [167]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [170]:
#For 3D,
a3 = np.arange(27).reshape((3,3,3))
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [174]:
a3[0, 1, :]

array([3, 4, 5])

In [175]:
a3[2, 1:, 1:]

array([[22, 23],
       [25, 26]])

In [176]:
a3[::2, 0, ::2]

array([[ 0,  2],
       [18, 20]])

In [177]:
a3[::2,1, ::2]

array([[ 3,  5],
       [21, 23]])

###ITERATING


In [178]:
print(a1, "\n")
print(a2, "\n")
print(a3, "\n")

[0 1 2 3 4 5 6 7 8 9] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 



In [179]:
for i in a1:
  print(i, end="\t")

0	1	2	3	4	5	6	7	8	9	

In [193]:
for i in a2:
  for j in i:
    print(j, end="\t")
  print('\n')


0	1	2	3	

4	5	6	7	

8	9	10	11	



In [192]:
for i in a3:
  for j in i:
    for k in j:
      print(k, end="\t")
    print('\n')
  print('\n')


0	1	2	

3	4	5	

6	7	8	



9	10	11	

12	13	14	

15	16	17	



18	19	20	

21	22	23	

24	25	26	





In [196]:
#or you could use nditer() function to loop through multiple dimension of array

for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


#RESHAPING

In [197]:
a1.reshape((2,5)) #reshape the shape of matrix

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [200]:
#transpose: the same tranpose matrix studied in highschool
print(a2, "\n")
a2.T
np.transpose(a2)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 



array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [202]:
#ravel: changes ndim array into a 1D arary
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

##STACKING


In [211]:
#stacking is like addigng the arrays either vertical or horizontally
s1 = np.random.random(4).reshape((2,2))
s1 = np.floor(s1 * 10)
s2 = np.random.random(4).reshape((2,2))
s2 = np.floor(s2 * 10)


In [218]:
x = np.hstack((s1, s2)) #horizontal stacking
x


array([[1., 1., 3., 5.],
       [7., 2., 9., 7.]])

In [219]:
y = np.vstack((s1, s2))
y

array([[1., 1.],
       [7., 2.],
       [3., 5.],
       [9., 7.]])

###SPLITING: OPP OF STACKING


In [223]:
np.hsplit(x, 2 ) #horizontal splitting

[array([[1., 1.],
        [7., 2.]]),
 array([[3., 5.],
        [9., 7.]])]

In [224]:
np.vsplit(y, 1)

[array([[1., 1.],
        [7., 2.],
        [3., 5.],
        [9., 7.]])]