In [14]:
import numpy as np
import random

In [18]:
a = np.random.randint(1, 100, 10 )
print(a)

[80 45 21 19 58 64 58 94  4 13]


np.sort(a) : creates a sorted array

In [20]:
np.sort(a)

array([ 4, 13, 19, 21, 45, 58, 58, 64, 80, 94], dtype=int32)

In [24]:
b = np.random.randint(1, 100, 10 ).reshape((2,5))
b

array([[69, 85, 85,  1, 30],
       [99, 84, 28,  9, 56]], dtype=int32)

In [26]:
print(np.sort(b, axis=0) ) # sort by column
print(np.sort(b, axis=1) ) # sort by row

[[69 84 28  1 30]
 [99 85 85  9 56]]
[[ 1 30 69 85 85]
 [ 9 28 56 84 99]]


In [30]:
print(np.append(a, 100)) # append a single value to the end of a
print(np.append(a, np.ones(6))) #append an array of ones to the end of a
print(np.append(b, np.ones((2,5)), axis=0)) # append 2 rows of ones to b
print(np.append(b, np.ones((2,5)), axis=1)) # append 2 columns of ones to b

[ 80  45  21  19  58  64  58  94   4  13 100]
[80. 45. 21. 19. 58. 64. 58. 94.  4. 13.  1.  1.  1.  1.  1.  1.]
[[69. 85. 85.  1. 30.]
 [99. 84. 28.  9. 56.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[[69. 85. 85.  1. 30.  1.  1.  1.  1.  1.]
 [99. 84. 28.  9. 56.  1.  1.  1.  1.  1.]]


In [31]:
np.concatenate((a, np.ones(6))) # concatenate a and an array of ones
np.concatenate((b, np.ones((2,5))), axis=0) # concatenate b and 2 rows of ones
np.concatenate((b, np.ones((2,5))), axis=1) # concatenate b     

array([[69., 85., 85.,  1., 30.,  1.,  1.,  1.,  1.,  1.],
       [99., 84., 28.,  9., 56.,  1.,  1.,  1.,  1.,  1.]])