In [1]:
import numpy as np

In [3]:
#speed
import time

a = [ i for i in range(1_000_000) ]
b = [ i for i in range(1_000_000, 2_000_000) ]

c = []

start = time.time()

for i in range(len(a)):
    c.append(a[i] + b[i])

print("Time taken for list: ", time.time() - start)

Time taken for list:  0.147538423538208


In [5]:
x = np.arange(1_000_000)
y = np.arange(1_000_000, 2_000_000)
start = time.time()
z = x + y
print("Time taken for numpy: ", time.time() - start)

Time taken for numpy:  0.02613353729248047


In [9]:
#interms of percentage improvement
print("Percentage improvement: ", (0.147538423538208 / 0.02613353729248047) * 100)

Percentage improvement:  564.5558880414553


In [ ]:
##Storage
import sys

a = [ i for i in range(1_000_000) ]

sys.getsizeof(a) # 8448728

8448728

In [16]:
b = np.arange(1_000_000, dtype=np.int32)
a = np.arange(1_000_000)
print(sys.getsizeof(a) ) ## 8000112 for in 64
print(sys.getsizeof(b)) ## 4000112 for int32

8000112
4000112


In [18]:
#fancy indexing
a = np.arange(24).reshape(4, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [19]:
# You can access specific rows and columns using fancy indexing
print(a[0]) # first row
print(a[:, 0]) # first column

[0 1 2 3 4 5]
[ 0  6 12 18]


In [22]:
# or you could access specific rows and columns which are not in order
print(a[[0, 2]]) # first and third row
print(a[:, [0, 2]]) # first and third column

[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]]
[[ 0  2]
 [ 6  8]
 [12 14]
 [18 20]]


In [31]:
x = np.random.random(24).reshape((4,6))

x = np.floor(x * 10)
x = x.astype(int)
x
#or

y = np.random.randint(0, 100, 24).reshape((4,6))
y

array([[29, 44, 81, 78, 86, 87],
       [26, 94, 78, 92,  0, 76],
       [72, 45, 61, 14, 83, 86],
       [72, 25, 47, 49, 54, 72]], dtype=int32)

In [32]:
y

array([[29, 44, 81, 78, 86, 87],
       [26, 94, 78, 92,  0, 76],
       [72, 45, 61, 14, 83, 86],
       [72, 25, 47, 49, 54, 72]], dtype=int32)

In [36]:
#boolean indexing is also possible
print(y > 40) # this will return a boolean array

[[False  True  True  True  True  True]
 [False  True  True  True False  True]
 [ True  True  True False  True  True]
 [ True False  True  True  True  True]]


In [37]:
y[y> 40] # this will return the values which are greater than 40

array([44, 81, 78, 86, 87, 94, 78, 92, 76, 72, 45, 61, 83, 86, 72, 47, 49,
       54, 72], dtype=int32)

In [39]:
y[y%2 != 0] # this will return the values which are not divisible by 2 (odd numbers)

array([29, 81, 87, 45, 61, 83, 25, 47, 49], dtype=int32)

### BROADCASTING

Broadcasting is the process of making the dimensions and the shape of the arrays equal. Here, the 1 will be added to the head of the smaller array to make of the same dimension and stretch that 1 to match the shape of the array

In [ ]:
a = np.arange(12).reshape(3,4)
b = np.random.randint(0, 100, 1)

In [ ]:
print(a)
print(b)

print(a + b) 
# broadcasting in action; Eventhough a and b have different shapes, numpy broadcasts b to match the shape of a

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[52]
[[52 53 54 55]
 [56 57 58 59]
 [60 61 62 63]]


In [43]:
# Creation of Mathematical functions

x = np.arange(10)

def sigmoid(x):
    return (1/(1 + np.exp(-x)))

sigmoid(x)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661])

In [67]:
# or MSE
y = np.random.randint(0, 2, 10)

py = np.random.uniform(0.01, 0.99, 10)


def mse(actual, pred):
    return np.mean((actual - pred) ** 2)

mse(y, py)

np.float64(0.29878356902348985)

In [69]:
# working with missing values

a = np.array([1, 2, np.nan, 4, 5])

a[~(np.isnan(a))]


array([1., 2., 4., 5.])

In [ ]:
# Plotting Graphs

